apiVersion: apps/v1
kind: Deployment
metadata:
  name: memento-mcp-server
  namespace: memento
  labels:
    app: memento-mcp-server
    version: v1.0.1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: memento-mcp-server
  template:
    metadata:
      labels:
        app: memento-mcp-server
        version: v1.0.1
    spec:
      containers:
      - name: memento-mcp-server
        image: srinmantest.azurecr.io/memento-mcp-server:v1.0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
          name: http
          protocol: TCP
        env:
        - name: MCP_SSE_HOST
          value: "0.0.0.0"
        - name: MCP_SSE_PORT
          value: "8000"
        - name: PYTHONUNBUFFERED
          value: "1"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        volumeMounts:
        - name: storage-volume
          mountPath: /app/memento_storage
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          runAsGroup: 1000
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          capabilities:
            drop:
            - ALL
      volumes:
      - name: storage-volume
        persistentVolumeClaim:
          claimName: memento-storage-pvc
      securityContext:
        fsGroup: 1000
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: memento-storage-pvc
  namespace: memento
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: managed-csi # Azure Files CSI driver
